Need to require shellwords
Fix this error if you run the test with just `rake`:

  1) Error:
ActivateTest#test_activate_gem_with_extensions:
NameError: uninitialized constant Gel::Package::Installer::GemInstaller::Shellwords